### ISSUE TITLE
City quarters

### ISSUE THREAD

**Issue by krlmlr** [zumbov2/RSwissMaps#2]
The large cities in Switzerland are subdivided in quarters, there even exist shapefiles. Last time I checked they weren't quite up to date, but I've made some effort to integrate them and to create a unified shapefile of Switzerland subdivided into municipalities + city quarters. Happy to share if you're interested.

**Comment by d-qn** [comment]
Cool, I think it could be part of #3

**Comment by krlmlr** [comment]
Updated shapes are available now: https://www.bfs.admin.ch/bfs/de/home/dienstleistungen/geostat/geodaten-bundesstatistik/administrative-grenzen/quartiergrenzen-schweizer-staedte.html. Need to double-check how well they fit now.
